# -*- coding: utf-8 -*-
"""TakeHomeBain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IYN3cSVPQaAqRrIBb5XwRpSRjdTvrLUn
"""

#importing required libraries
import requests
import pandas as pd

#after inspecting webpage i was able to find out this api which basically pulls all locations in one single request
url = "https://lamadeleine.com/wp-json/wp/v2/restaurant-locations"

#params
querystring = {"per_page":"150"}

#header
headers = {

    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
}

#performing get operation to recieve the data from the url
response = requests.request("GET", url, headers=headers, params=querystring)

#adding the data in data in json format
data = response.json()

#this operation takes care of normalizing the json into tabular format
df=pd.json_normalize(data)

#this operation takes care of selecting specific data that we want from that total of 290+ columns
df1 = df[['id', 'acf.locationHero.id', 'acf.locationHero.storeName', 'acf.locationHero.addressLine1', 'acf.locationHero.addressLine2', 'acf.locationHero.city', 'acf.locationHero.state', 'acf.locationHero.zip', 'acf.locationHero.phone']]


#this operation takes care of renaming those complex columns into simple readable columns
df1 = df1.rename(columns={
    'id': 'storeID',
    'acf.locationHero.id': 'location ID',
    'acf.locationHero.storeName': 'locationName',
    'acf.locationHero.addressLine1': 'streetAddress_1',
    'acf.locationHero.addressLine2': 'streetAddress_2',
    'acf.locationHero.city': 'City',
    'acf.locationHero.state': 'State',
    'acf.locationHero.zip': 'PostalCode',
    'acf.locationHero.phone': 'phoneNumber'
})

#some states were in the format of 'texas' changed it to 'TX' for better visualization.
df1['State'] = df1['State'].replace('Texas', 'TX')

#concate add_1 and add_2
df1['streetAddress'] = df1['streetAddress_1'] + ' ' + df1['streetAddress_2']

#selecting final columns
df1 = df1[['storeID', 'location ID', 'locationName', 'streetAddress', 'City', 'State', 'PostalCode', 'phoneNumber']]


print(df1)
#use this to create csv
#df1.to_csv('restaurant_locations.csv', index=False)